### ISSUE TITLE
Add support for Strong Params

### ISSUE THREAD

**Issue by liveh2o** [liveh2o/active_remote#27]
Active Record now enforces attribute whitelisting through Strong Params, but ARem doesn't support it. It should.

**Comment by liveh2o** [comment]
Not actually an issue. Active Record has nothing to do with Strong Params.

**Comment by brianstien** [comment]
This is still a problem, here is an example

```ruby
class User < ::ActiveRecord::Base
end

UsersController < ::ApplicationController::Base
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user]) # raises ActiveModel::ForbiddenAttributes because params have not been sanitized with strong params
  end
end
```

```ruby
class User < ::ActiveRemote::Base
end

UsersController < ::ApplicationController::Base
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user]) # does not raise an error, allows mass assignment vulnerability
  end
end
```

**Comment by brianstien** [comment]
I think we need to include `ActiveModel::ForbiddenAttributesProtection` into ActiveRemote::Base

https://github.com/cgriego/active_attr#massassignment

**Comment by liveh2o** [comment]
Tricky. I'll get something up soon.

**Comment by liveh2o** [comment]
Closing this because the work on v3.0 (#36) covers it.
