### ISSUE TITLE
Support `update` as an alias for `update_attributes`

### ISSUE THREAD

**Issue by brianstien** [liveh2o/active_remote#32]
Rails 4 added `update` as an alias for `update_attributes`, and generators will now use `update` instead of `update_attributes`.  It seems that `update` is now the preferred method.

http://apidock.com/rails/v4.2.1/ActiveRecord/Persistence/update

**Comment by liveh2o** [comment]
:+1:

**Comment by liveh2o** [comment]
Resolved by #34.
