### ISSUE TITLE
ActiveRemote 3.0 feature set

### ISSUE THREAD

**Issue by brianstien** [liveh2o/active_remote#36]
I wanted to start working on the 3.0 release.

Items that will be included
- [x] Strong params enabled by default
- [x] Drop support for protected attributes
- [x] Remove deprecated methods
- [x] ~~Fully pluggable/configurable rpc adapter interface~~
- [x] Remove active_attr dependency
- [x] Drop support for Rails 3
- [x] Investigate performance of `write_attribute` method
- [x] Investigate handoff between protobuf adapter and active remote
- [x] Remove publishable module
- [x] Extract active_remote-bulk
- [x] Delete core extensions
- [x] Refactor attribute internals

**Comment by liveh2o** [comment]
Closing this now that all of the work is done and we're ready to cut an RC.
