### ISSUE TITLE
Type Casting Problems

### ISSUE THREAD

**Issue by film42** [liveh2o/active_remote#37]
We know there are some type casting issues that we've resolved internally, but still need to either be fixed here or in `attr_model`.

I noticed we are using additional type casting on the `Field` class which is undoing some of our internal optimizations: https://github.com/liveh2o/active_remote/blob/db2d3efdccd458e3075d6d6fc8e8e90540e8bb4e/lib/active_remote/serializers/protobuf.rb#L129-L134

This is called for every `repeated?` field on every search request. Aka, a lot.

cc @liveh2o @abrandoned

**Comment by liveh2o** [comment]
Typecasting has been pulled into ARem (# ), so this is no longer an issue.
