### ISSUE TITLE
leaking method sites on activemodel attributes

### ISSUE THREAD

**Issue by abrandoned** [liveh2o/active_remote#60]
Not sure where the leak is, but this method defines a new method when a proxy is created for the attributes that are defined https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/attribute_methods.rb#L383

the value of `__FILE__` is stored > 14,000 times in a single running process of synchronicity-subscriber ... this is the only spot this is called; may be because of JRuby (and not active_remote), but my assumption is active_remote because we recently refactored the methods that influence if a method is generated ... looking for additional evidence

@liveh2o @brianstien

**Comment by abrandoned** [comment]
may be a jruby problem ... the system gets to a steady state after defining methods on the models and doesn't continue redefining them ... so the file string being present 14,000+ times in a heap dump must be related to the internals of how method definitions are stored (but does not manifest elsewhere)

**Comment by liveh2o** [comment]
Is this still relevant, @abrandoned?

**Comment by liveh2o** [comment]
Closing since this appears related to Rails 4.2, and we're now supporting 6.0 here.
